version: '3.7'

services:
  db:
    image: postgres:12-alpine
    environment:
      "POSTGRES_USER": "postgres"
      "POSTGRES_PASSWORD": "postgres"
      "POSTGRES_DB": "fastapi"
      "PGDATA": "/var/lib/postgresql/data"
    ports:
      - 5433:5432
    volumes:
      # - ./notification-backend:/usr/src/app
      - pg_data:/var/lib/postgresql/data
    logging:
      driver: none
    networks: 
      - notification

  api:
    image: raton/notification-backend:latest
    restart: always
    # volumes:
      # - ./notification-backend:/usr/src/app
    ports:
      - 8000:8000
    links: 
      - db
    tty: true
    networks: 
      - notification

  web: 
    image: raton/notification-frontend:latest
    restart: always
    ports:
      - 8001:8001
    tty: true
    networks: 
      - notification

networks:
  notification:
    driver: "bridge"
volumes:
  pg_data:
    driver: "local"
    name: notification_shared_data_volume_pg
